{% set name = "voluptuous" %}
{% set version = "0.11.7" %}
{% set sha256 = "2abc341dbc740c5e2302c7f9b8e2e243194fb4772585b991931cb5b22e9bf456" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - flake8

  run:
    - python

test:
  imports:
    - voluptuous

about:
  home: https://github.com/alecthomas/voluptuous
  license: BSD3
  license_file: COPYING
  summary: Voluptuous is a Python data validation library

extra:
  recipe-maintainers:
    - tusharmakkar08
    - vamega
