travis:
  secure:
    BINSTAR_TOKEN: y1mQbKGvOiD7eOustT6CE7DeVwqxXg9pQY4DQczqAKjrvfGGDRJddOZD9w2AMb4N5xj8j79ZkYi/dcTKu6qnS4lNQr696HGDuil1j9VHiiTgXBj0cO9Fgk25MoGOg3DOd7TXdPWIzCYJk+y4te6Hn2AyBE6MP9/aPUvewJOU1wGdsUoK6WRAbTbtJAxt56cacHGq6+SIG9O5uCXDpgpgdzZPL6HmSzDPdHNxPB6JT4DhZiBbrbvZoRNi49xuqktY7MQ4t+NPHQUqaCtk/WIPoyemDONMFbZ1uBVogTPrBxMyBB9VEZQ3ycqW1CboaX+pLI1rSFRgrqF/RzCRj5h2tQcgd1dITMirPYkwy1zo5oU5m/ttKBmsuyVK5qlmwuelDWKv7bEjw5JXXfTBjRNbPD/1NRMlJz8hZ6QkAwSS+0F09zAMjQjaslN0XCNwxeJVF7oF9uqs5cvMJYpmUAczzxNBO12mX9iiGVUTOXUJV24NhS14p6AFPrwT1BpZ/5ATHdPHipzKCOv6cFlaOyo7G9PdZmwOB0ivNBglIALYB/M7qgPn0DvrRttBXVrpuWMGP5mu4ZphUz0/yd5dzj+hpijtFFyzOHopmUjECoOA1WXN2qU1B/vRptwFNd9j+VUhHq/Y353tJSa9p2+JwAJJ++x8B4jemiVaLKbj8gnraaI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
