travis:
  secure:
    BINSTAR_TOKEN: J2kzgkP6GVLbWA0VcBzAUbC/BiWfC2EwHv1EOsh/xiRKQHDtzeQdcoO14oDRkfNLZvKbsxEhes+OywCkSc7DWW2k9lhWRH3pGjFq8Dr7xm8ldjT+IBSL6z1kVX4wHVNbvvgbOlccqgEP00WH1+gSpAUya9wbXtT97PJYslGE32VZ9PkA4j2OUQwwhD/6p4nSHEL3qRNXUi4HhZc9kNDG/GQfgIYrTlzX50/tW1K7x7nAoW+2yt94Scy5n4PWADZmco/DEJFe0h9Jw2i9+Ns+awdqfN0rAFu6NGZe0iKpxj1dLmQK3HfWy0wmxi+t/dYPLsZG65Yr/7CI8sn27e6CgBytpNOU11uGH5tQQoGIhQwQ9hW9Q0t8af7TQmemxha/CQr9cDQwSW1Xx6Ezzbn4CF12W9yq8a1N7ZiqGbtCa/cnAPJrS4TT+UM1vXTSKaGNk7WvRGgnJEpdjflW+bpeExJJ8evNWD4kzFgcMNdBJ26JdKROD5RqGDT3n3oMxUk1TCQmT6//bpmJjFfXnbc0AtHrIvG3XlzE1faXIwe0PjI8rh8spluIBTi4sH3Z/EL4uVWgaM0kZYQVkLuom9BEwTAnqKTn0WKylDowLkuoccLcfpnhydzBGsuS+tFlZD4um6vy3dS3zJah7xbOogRsH/ijt5p073drHC1XRFa2Kx0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
