travis:
  secure:
    BINSTAR_TOKEN: DeZWfjlxGwZjJ1rDyLpPBdlSmQPWPLinzW05UYsQIMU5Kch8FMo9bSclMI/KmK43oPVdwOqY+ymd4Nq0wKFq+jFtljsR97woHbj0F1Wc5AYJ6YQdHIapDv5jTxr6w/doVlgQRtRw3Ds4mtl00UQsHTzaIXhONJGnCYnsme0L4GAMIoQxjhZEx6sBN9SdxPn9xd0GNVIxYsAUrha2oRc2lqPmd8sESZGdJkDdS0MMsi25q9LZC4eM0witLeCpRMdG8mJljyi75TvIXbYlijIumLkpVMtt3LmDgDcE9NvDVY8W9DPL7WZsdLe8Ea3uq6wBd6Lu3nxs5YDRAQHqulFKCUb8A5fwOhJwm15O2efo16wwbZ6d7yOVLWaapizjOMMWyQKiVlLKM4KpKH8krZrz1y+4su2d1fcaJBvVLriQsSP9YJGf/nLS8F1lA3bnruh7kho4HQGpGKkzIBmb5dQfxjuGktgqM2RZeUP53LfErUTpb60v1zDrP1vGDO8RcZ/R0nX98ssTn2H7YH603aAxKY9Mv2PsQXMHXZKvTkBL1FmCCjr7bve56o066S4Ww52/lpuA08v3M1QJCm4gxScEksnfWB4w4dolxes9nX5i09NvqHCFDBxNQUjc30Zyw0GYDiFB5+xcLed6pw7zM/Fmf7khGGNLmxVEjZ1GpW1x0Lg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
